# Generated by Django 2.1.5 on 2019-01-16 08:49

from django.db import migrations

def populate_roles_table(apps, schema_editor):

    roles = ['manager', 'user']
    role = apps.get_model('accounts', 'Role')
    for r in roles:
        role.objects.create(name=r)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_roles_table)
    ]
